# Generated by Django 4.2 on 2024-05-15 08:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0002_widget_css'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_json', models.JSONField()),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widget.widget')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
