# Generated by Django 5.0.3 on 2024-05-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0003_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='form_name',
            field=models.TextField(default='form_name'),
        ),
    ]
