# Generated by Django 4.2 on 2024-05-30 13:16

from django.db import migrations, models
import django.db.models.deletion
import uuid
import widget.models.data_files_model


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0004_widget_form_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('files', models.FileField(upload_to=widget.models.data_files_model.file_upload_path)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widget.widget')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
