# Generated by Django 4.2 on 2024-08-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0005_datafiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='selection',
            field=models.TextField(default='database'),
        ),
    ]
